### ISSUE TITLE
ValueError: On entry to SGESDD parameter number 12 had an illegal value 

### ISSUE THREAD

**Issue by ericustc** [cyh24/Joint-Bayesian#1]
python test_lfw.py

(71846, 5900) (71846, 1)
2015-10-27, 19:18:08  PCA training (n_components=2000)...
Traceback (most recent call last):
  File "test_lfw.py", line 64, in <module>
    excute_train()
  File "test_lfw.py", line 22, in excute_train
    pca = PCA_Train(data, result_fold)
  File "/opt/wjc/Joint-Bayesian/src/joint_bayesian.py", line 122, in PCA_Train
    pca.fit(data)
  File "/usr/lib64/python2.7/site-packages/sklearn/decomposition/pca.py", line 221, in fit
    self._fit(X)
  File "/usr/lib64/python2.7/site-packages/sklearn/decomposition/pca.py", line 271, in _fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File "/usr/lib64/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 104, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
ValueError: On entry to SGESDD parameter number 12 had an illegal value

what's your method of solving the error?

**Comment by lufo816** [comment]
Use IncrementalPCA()

**Comment by HKUSTmji** [comment]
the same problem, even replacing the PCA method to the IncrementalPCA. Any suggestions?

**Comment by leandrosnm** [comment]
Hi, I had the same issue and solved it by using IncrementalPCA() and updating numpy to version 1.11.0 and scipy to version 0.17.0

It seems there's a bug somewhere in numpy and scipy older versions.

**Comment by zjz5250** [comment]
@ericustc,  can you share  the data?   l can not  download .  thanks
